name: Pinata Deploy

on:
  push:
    branches:
      - master
      - develop

jobs:
  deploy-master:
    name: Deploy-Master

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1

      - name: Install ipfs-deploy
        run: npm install -g ipfs-deploy

      - name: Install dependencies
        run: npm install

      - name: Build Kovan
        run: npm run build-pinata
        env:
          APP_CHAIN_ID: 42
          APP_GAS_PRICE: 100000000000

      - name: Deploy Kovan
        run: ipfs-deploy ./dist -p pinata -d cloudflare
        env:
          IPFS_DEPLOY_PINATA__API_KEY: ${{ secrets.IPFS_DEPLOY_PINATA__API_KEY }}
          IPFS_DEPLOY_PINATA__SECRET_API_KEY: ${{ secrets.IPFS_DEPLOY_PINATA__SECRET_API_KEY }}
          IPFS_DEPLOY_CLOUDFLARE__API_TOKEN: ${{ secrets.IPFS_DEPLOY_CLOUDFLARE__API_TOKEN }}
          IPFS_DEPLOY_CLOUDFLARE__ZONE: balancer.exchange
          IPFS_DEPLOY_CLOUDFLARE__RECORD: _dnslink.kovan-test.balancer.exchange

      - name: Build Mainnet
        run: npm run build-pinata
        env:
          APP_CHAIN_ID: 1
          APP_GAS_PRICE: 100000000000

      - name: Deploy Mainnet
        run: ipfs-deploy ./dist -p pinata -d cloudflare
        env:
          IPFS_DEPLOY_PINATA__API_KEY: ${{ secrets.IPFS_DEPLOY_PINATA__API_KEY }}
          IPFS_DEPLOY_PINATA__SECRET_API_KEY: ${{ secrets.IPFS_DEPLOY_PINATA__SECRET_API_KEY }}
          IPFS_DEPLOY_CLOUDFLARE__API_TOKEN: ${{ secrets.IPFS_DEPLOY_CLOUDFLARE__API_TOKEN }}
          IPFS_DEPLOY_CLOUDFLARE__ZONE: balancer.exchange
          IPFS_DEPLOY_CLOUDFLARE__RECORD: _dnslink.balancer.exchange-test.balancer.exchange

  deploy-develop:
    name: Deploy-Develop

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/develop'

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1

      - name: Install ipfs-deploy
        run: npm install -g ipfs-deploy

      - name: Install dependencies
        run: npm install

      - name: Build Beta
        run: npm run build-pinata
        env:
          APP_CHAIN_ID: 1
          APP_GAS_PRICE: 100000000000

      - name: Deploy Beta
        run: ipfs-deploy ./dist -p pinata -d cloudflare
        env:
          IPFS_DEPLOY_PINATA__API_KEY: ${{ secrets.IPFS_DEPLOY_PINATA__API_KEY }}
          IPFS_DEPLOY_PINATA__SECRET_API_KEY: ${{ secrets.IPFS_DEPLOY_PINATA__SECRET_API_KEY }}
          IPFS_DEPLOY_CLOUDFLARE__API_TOKEN: ${{ secrets.IPFS_DEPLOY_CLOUDFLARE__API_TOKEN }}
          IPFS_DEPLOY_CLOUDFLARE__ZONE: balancer.exchange
          IPFS_DEPLOY_CLOUDFLARE__RECORD: _dnslink.beta-test.balancer.exchange
